#define TIN_CAN_SSID "<wifi-name>"
#define TIN_CAN_PASSWORD "<wifi-password>"
#define TIN_CAN_ID "<can-name>"
#define TIN_CAN_SWITCH_HOST "<local ip address>"
#define TIN_CAN_SWITCH_PORT "<local port>"
